// Code generated by qtc from "Body-Old.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/Old/Body-Old.qtpl:1
package Old

//line views/Old/Body-Old.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/Old/Body-Old.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/Old/Body-Old.qtpl:1
func StreamBody(qw422016 *qt422016.Writer) {
//line views/Old/Body-Old.qtpl:1
	qw422016.N().S(`
  <body>
    <!-- ===============================================-->
    <!--    Main Content-->
    <!-- ===============================================-->
    <main class="main">
      <h1>Hello - Testing icon. <i class="fa fa-bullhorn"></i>
       <i class="material-icons">face</i></h1> 

      `)
//line views/Old/Body-Old.qtpl:10
	StreamTopNavigation(qw422016)
//line views/Old/Body-Old.qtpl:10
	qw422016.N().S(`
      <div id="vueApp">
         <v-app>
            <v-main>
               <v-container>
	           <div class="row align-items-center">
	        		<h2>Script Vue Table Interaction</h2>
                   </div>
	           <div class="row align-items-center">
                                `)
//line views/Old/Body-Old.qtpl:19
	StreamScriptsTableVue(qw422016)
//line views/Old/Body-Old.qtpl:19
	qw422016.N().S(`
	           </div>
               </v-container>
            </v-main>
         </v-app>
      </div>

      <section class="pt-4 pt-md-5">
	        <div class="container">
	         	<div class="row align-items-center">
	        		<h2>Script Interaction</h2>
                        </div>
	         	<div class="row align-items-center">
                                `)
//line views/Old/Body-Old.qtpl:32
	StreamScriptsTable(qw422016)
//line views/Old/Body-Old.qtpl:32
	qw422016.N().S(`
	        	</div>
	        </div>
      </section>


      <!-- ============================================-->
      <section class="text-center border-top footer-text py-3">

        <!-- <div class="container">Made with ❤️ by <a class="text-500 text-decoration-none">Me </a> -->
        <!-- </div> -->
        <!-- end of .container-->

      </section>
      <!-- <section> close ============================-->
      <!-- ============================================-->


    </main>

    `)
//line views/Old/Body-Old.qtpl:52
	StreamAlertBoxModal(qw422016)
//line views/Old/Body-Old.qtpl:52
	qw422016.N().S(`

    `)
//line views/Old/Body-Old.qtpl:54
	StreamScriptInteractionModal(qw422016)
//line views/Old/Body-Old.qtpl:54
	qw422016.N().S(`

    <!-- ===============================================-->
    <!--    JavaScripts-->
    <!-- ===============================================-->
    <!-- JavaScript and dependencies -->
    <script src="_assets/js/jquery-3.5.1.min.js"></script>
    <script src="_assets/js/popper.min.js"></script>
    <script src="_assets/bootstrap-5.0.0-alpha1-dist/js/bootstrap.min.js"></script>
    <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script> 
    <script src="_assets/js/bootstrap-5.0.0.min.js"></script> -->
    <script src="_assets/js/plugins.js"></script>
    <script src="_assets/lib/is/is.min.js"></script>
    <script src="_assets/lib/stickyfilljs/stickyfill.min.js"></script>
    <script src="_assets/js/theme.js"></script>
    <script src="_assets/js/jsrender.min.js"></script>

    <!-- For Vue Modules. -->
    <script type="text/javascript" src="vue/libs/vue2.js"></script>
    <script type="text/javascript" src="vue/libs/vuex-3.6.0.js"></script>
    <script type="text/javascript" src="vue/libs/vuetify.min.js"></script>
    <script type="text/javascript" src="vue/libs/axios.min.js"></script>
    <script type="text/javascript" src="vue/libs/gcare-httpVueLoader.js"></script>
    <script type="text/javascript" src="vue/libs/gcare-httpVueLoader-addon.js"></script>
    <script type="text/javascript" src="vue/vuejs-dialog-orig/dist/vuejs-dialog.min.js"></script>

   <!-- Finally our standard code if any -->
   <script src="_assets/js/index-cleaned.js"></script>

   <!-- Whatever is generated by template system. -->
   <script src="_assets/js/index-autogen.js"></script> 

   `)
//line views/Old/Body-Old.qtpl:86
	StreamJS_ScriptActionTemplatesVue(qw422016)
//line views/Old/Body-Old.qtpl:86
	qw422016.N().S(`

   <script>

   `)
//line views/Old/Body-Old.qtpl:90
	StreamJS_StoreVue(qw422016)
//line views/Old/Body-Old.qtpl:90
	qw422016.N().S(`

    new Vue({
      el: '#vueApp',
      store: store,
      vuetify: new Vuetify({
         icons: {
            iconfont: 'fa'
         }
      }),
    })

   </script>

  </body>
`)
//line views/Old/Body-Old.qtpl:105
}

//line views/Old/Body-Old.qtpl:105
func WriteBody(qq422016 qtio422016.Writer) {
//line views/Old/Body-Old.qtpl:105
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/Old/Body-Old.qtpl:105
	StreamBody(qw422016)
//line views/Old/Body-Old.qtpl:105
	qt422016.ReleaseWriter(qw422016)
//line views/Old/Body-Old.qtpl:105
}

//line views/Old/Body-Old.qtpl:105
func Body() string {
//line views/Old/Body-Old.qtpl:105
	qb422016 := qt422016.AcquireByteBuffer()
//line views/Old/Body-Old.qtpl:105
	WriteBody(qb422016)
//line views/Old/Body-Old.qtpl:105
	qs422016 := string(qb422016.B)
//line views/Old/Body-Old.qtpl:105
	qt422016.ReleaseByteBuffer(qb422016)
//line views/Old/Body-Old.qtpl:105
	return qs422016
//line views/Old/Body-Old.qtpl:105
}

//line views/Old/Body-Old.qtpl:108
func StreamJSCodeForBody(qw422016 *qt422016.Writer) {
//line views/Old/Body-Old.qtpl:108
	qw422016.N().S(`
 <!-- All JS functions which are related to main body. -->

   `)
//line views/Old/Body-Old.qtpl:111
	StreamJavascript_AlertBox(qw422016)
//line views/Old/Body-Old.qtpl:111
	qw422016.N().S(`

`)
//line views/Old/Body-Old.qtpl:113
}

//line views/Old/Body-Old.qtpl:113
func WriteJSCodeForBody(qq422016 qtio422016.Writer) {
//line views/Old/Body-Old.qtpl:113
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/Old/Body-Old.qtpl:113
	StreamJSCodeForBody(qw422016)
//line views/Old/Body-Old.qtpl:113
	qt422016.ReleaseWriter(qw422016)
//line views/Old/Body-Old.qtpl:113
}

//line views/Old/Body-Old.qtpl:113
func JSCodeForBody() string {
//line views/Old/Body-Old.qtpl:113
	qb422016 := qt422016.AcquireByteBuffer()
//line views/Old/Body-Old.qtpl:113
	WriteJSCodeForBody(qb422016)
//line views/Old/Body-Old.qtpl:113
	qs422016 := string(qb422016.B)
//line views/Old/Body-Old.qtpl:113
	qt422016.ReleaseByteBuffer(qb422016)
//line views/Old/Body-Old.qtpl:113
	return qs422016
//line views/Old/Body-Old.qtpl:113
}

//line views/Old/Body-Old.qtpl:116
func StreamCSSCodeForBody(qw422016 *qt422016.Writer) {
//line views/Old/Body-Old.qtpl:116
	qw422016.N().S(`
   `)
//line views/Old/Body-Old.qtpl:117
	StreamCSSForAlertBox(qw422016)
//line views/Old/Body-Old.qtpl:117
	qw422016.N().S(`
`)
//line views/Old/Body-Old.qtpl:118
}

//line views/Old/Body-Old.qtpl:118
func WriteCSSCodeForBody(qq422016 qtio422016.Writer) {
//line views/Old/Body-Old.qtpl:118
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/Old/Body-Old.qtpl:118
	StreamCSSCodeForBody(qw422016)
//line views/Old/Body-Old.qtpl:118
	qt422016.ReleaseWriter(qw422016)
//line views/Old/Body-Old.qtpl:118
}

//line views/Old/Body-Old.qtpl:118
func CSSCodeForBody() string {
//line views/Old/Body-Old.qtpl:118
	qb422016 := qt422016.AcquireByteBuffer()
//line views/Old/Body-Old.qtpl:118
	WriteCSSCodeForBody(qb422016)
//line views/Old/Body-Old.qtpl:118
	qs422016 := string(qb422016.B)
//line views/Old/Body-Old.qtpl:118
	qt422016.ReleaseByteBuffer(qb422016)
//line views/Old/Body-Old.qtpl:118
	return qs422016
//line views/Old/Body-Old.qtpl:118
}
