// Code generated by qtc from "Alert.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// info, warning, danger, primary, light
//

//line widgets/Alert.qtpl:3
package widgets

//line widgets/Alert.qtpl:3
import . "../types"

//line widgets/Alert.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line widgets/Alert.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line widgets/Alert.qtpl:5
func StreamAlert(qw422016 *qt422016.Writer, opt *WidgetInfo) {
//line widgets/Alert.qtpl:5
	qw422016.N().S(`
<div class="alert alert-info alert-dismissible">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong>`)
//line widgets/Alert.qtpl:8
	qw422016.E().S(opt.HighlightText)
//line widgets/Alert.qtpl:8
	qw422016.N().S(`</strong> `)
//line widgets/Alert.qtpl:8
	qw422016.E().S(opt.Text)
//line widgets/Alert.qtpl:8
	qw422016.N().S(`
</div>
`)
//line widgets/Alert.qtpl:10
}

//line widgets/Alert.qtpl:10
func WriteAlert(qq422016 qtio422016.Writer, opt *WidgetInfo) {
//line widgets/Alert.qtpl:10
	qw422016 := qt422016.AcquireWriter(qq422016)
//line widgets/Alert.qtpl:10
	StreamAlert(qw422016, opt)
//line widgets/Alert.qtpl:10
	qt422016.ReleaseWriter(qw422016)
//line widgets/Alert.qtpl:10
}

//line widgets/Alert.qtpl:10
func Alert(opt *WidgetInfo) string {
//line widgets/Alert.qtpl:10
	qb422016 := qt422016.AcquireByteBuffer()
//line widgets/Alert.qtpl:10
	WriteAlert(qb422016, opt)
//line widgets/Alert.qtpl:10
	qs422016 := string(qb422016.B)
//line widgets/Alert.qtpl:10
	qt422016.ReleaseByteBuffer(qb422016)
//line widgets/Alert.qtpl:10
	return qs422016
//line widgets/Alert.qtpl:10
}

//line widgets/Alert.qtpl:12
func StreamAlertInfo(qw422016 *qt422016.Writer, opt *WidgetInfo) {
//line widgets/Alert.qtpl:12
	qw422016.N().S(`
<div class="alert alert-info alert-dismissible">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong>`)
//line widgets/Alert.qtpl:15
	qw422016.E().S(opt.HighlightText)
//line widgets/Alert.qtpl:15
	qw422016.N().S(`</strong> `)
//line widgets/Alert.qtpl:15
	qw422016.E().S(opt.Text)
//line widgets/Alert.qtpl:15
	qw422016.N().S(`
</div>
`)
//line widgets/Alert.qtpl:17
}

//line widgets/Alert.qtpl:17
func WriteAlertInfo(qq422016 qtio422016.Writer, opt *WidgetInfo) {
//line widgets/Alert.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line widgets/Alert.qtpl:17
	StreamAlertInfo(qw422016, opt)
//line widgets/Alert.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line widgets/Alert.qtpl:17
}

//line widgets/Alert.qtpl:17
func AlertInfo(opt *WidgetInfo) string {
//line widgets/Alert.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
//line widgets/Alert.qtpl:17
	WriteAlertInfo(qb422016, opt)
//line widgets/Alert.qtpl:17
	qs422016 := string(qb422016.B)
//line widgets/Alert.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
//line widgets/Alert.qtpl:17
	return qs422016
//line widgets/Alert.qtpl:17
}

//line widgets/Alert.qtpl:19
func StreamAlertDanger(qw422016 *qt422016.Writer, opt *WidgetInfo) {
//line widgets/Alert.qtpl:19
	qw422016.N().S(`
<div class="alert alert-info alert-dismissible">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong>`)
//line widgets/Alert.qtpl:22
	qw422016.E().S(opt.HighlightText)
//line widgets/Alert.qtpl:22
	qw422016.N().S(`</strong> `)
//line widgets/Alert.qtpl:22
	qw422016.E().S(opt.Text)
//line widgets/Alert.qtpl:22
	qw422016.N().S(`
</div>
`)
//line widgets/Alert.qtpl:24
}

//line widgets/Alert.qtpl:24
func WriteAlertDanger(qq422016 qtio422016.Writer, opt *WidgetInfo) {
//line widgets/Alert.qtpl:24
	qw422016 := qt422016.AcquireWriter(qq422016)
//line widgets/Alert.qtpl:24
	StreamAlertDanger(qw422016, opt)
//line widgets/Alert.qtpl:24
	qt422016.ReleaseWriter(qw422016)
//line widgets/Alert.qtpl:24
}

//line widgets/Alert.qtpl:24
func AlertDanger(opt *WidgetInfo) string {
//line widgets/Alert.qtpl:24
	qb422016 := qt422016.AcquireByteBuffer()
//line widgets/Alert.qtpl:24
	WriteAlertDanger(qb422016, opt)
//line widgets/Alert.qtpl:24
	qs422016 := string(qb422016.B)
//line widgets/Alert.qtpl:24
	qt422016.ReleaseByteBuffer(qb422016)
//line widgets/Alert.qtpl:24
	return qs422016
//line widgets/Alert.qtpl:24
}

//line widgets/Alert.qtpl:26
func StreamAlertPrimary(qw422016 *qt422016.Writer, opt *WidgetInfo) {
//line widgets/Alert.qtpl:26
	qw422016.N().S(`
<div class="alert alert-info alert-dismissible">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong>`)
//line widgets/Alert.qtpl:29
	qw422016.E().S(opt.HighlightText)
//line widgets/Alert.qtpl:29
	qw422016.N().S(`</strong> `)
//line widgets/Alert.qtpl:29
	qw422016.E().S(opt.Text)
//line widgets/Alert.qtpl:29
	qw422016.N().S(`
</div>
`)
//line widgets/Alert.qtpl:31
}

//line widgets/Alert.qtpl:31
func WriteAlertPrimary(qq422016 qtio422016.Writer, opt *WidgetInfo) {
//line widgets/Alert.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line widgets/Alert.qtpl:31
	StreamAlertPrimary(qw422016, opt)
//line widgets/Alert.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line widgets/Alert.qtpl:31
}

//line widgets/Alert.qtpl:31
func AlertPrimary(opt *WidgetInfo) string {
//line widgets/Alert.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line widgets/Alert.qtpl:31
	WriteAlertPrimary(qb422016, opt)
//line widgets/Alert.qtpl:31
	qs422016 := string(qb422016.B)
//line widgets/Alert.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line widgets/Alert.qtpl:31
	return qs422016
//line widgets/Alert.qtpl:31
}

//line widgets/Alert.qtpl:33
func StreamAlertLight(qw422016 *qt422016.Writer, opt *WidgetInfo) {
//line widgets/Alert.qtpl:33
	qw422016.N().S(`
<div class="alert alert-info alert-dismissible">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong>`)
//line widgets/Alert.qtpl:36
	qw422016.E().S(opt.HighlightText)
//line widgets/Alert.qtpl:36
	qw422016.N().S(`</strong> `)
//line widgets/Alert.qtpl:36
	qw422016.E().S(opt.Text)
//line widgets/Alert.qtpl:36
	qw422016.N().S(`
</div>
`)
//line widgets/Alert.qtpl:38
}

//line widgets/Alert.qtpl:38
func WriteAlertLight(qq422016 qtio422016.Writer, opt *WidgetInfo) {
//line widgets/Alert.qtpl:38
	qw422016 := qt422016.AcquireWriter(qq422016)
//line widgets/Alert.qtpl:38
	StreamAlertLight(qw422016, opt)
//line widgets/Alert.qtpl:38
	qt422016.ReleaseWriter(qw422016)
//line widgets/Alert.qtpl:38
}

//line widgets/Alert.qtpl:38
func AlertLight(opt *WidgetInfo) string {
//line widgets/Alert.qtpl:38
	qb422016 := qt422016.AcquireByteBuffer()
//line widgets/Alert.qtpl:38
	WriteAlertLight(qb422016, opt)
//line widgets/Alert.qtpl:38
	qs422016 := string(qb422016.B)
//line widgets/Alert.qtpl:38
	qt422016.ReleaseByteBuffer(qb422016)
//line widgets/Alert.qtpl:38
	return qs422016
//line widgets/Alert.qtpl:38
}
