// Code generated by qtc from "InfoBox.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// whiptail --title "Example Title" --infobox "This is an example info box." 8 70
// Here, there is no OK prompt, May be only close. The idea could be to display something to user, but to continue the execution without waiting.
//

//line widgets/InfoBox.qtpl:4
package widgets

//line widgets/InfoBox.qtpl:4
import . "../types"

//line widgets/InfoBox.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line widgets/InfoBox.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line widgets/InfoBox.qtpl:6
func StreamInfoBox(qw422016 *qt422016.Writer, opt *WidgetInfo) {
//line widgets/InfoBox.qtpl:6
	qw422016.N().S(`
    <div class="row">
        <div id="`)
//line widgets/InfoBox.qtpl:8
	qw422016.E().S(opt.Id)
//line widgets/InfoBox.qtpl:8
	qw422016.N().S(`" class="text-center">`)
//line widgets/InfoBox.qtpl:8
	qw422016.E().S(opt.Message)
//line widgets/InfoBox.qtpl:8
	qw422016.N().S(`</div>
    </div>
`)
//line widgets/InfoBox.qtpl:10
}

//line widgets/InfoBox.qtpl:10
func WriteInfoBox(qq422016 qtio422016.Writer, opt *WidgetInfo) {
//line widgets/InfoBox.qtpl:10
	qw422016 := qt422016.AcquireWriter(qq422016)
//line widgets/InfoBox.qtpl:10
	StreamInfoBox(qw422016, opt)
//line widgets/InfoBox.qtpl:10
	qt422016.ReleaseWriter(qw422016)
//line widgets/InfoBox.qtpl:10
}

//line widgets/InfoBox.qtpl:10
func InfoBox(opt *WidgetInfo) string {
//line widgets/InfoBox.qtpl:10
	qb422016 := qt422016.AcquireByteBuffer()
//line widgets/InfoBox.qtpl:10
	WriteInfoBox(qb422016, opt)
//line widgets/InfoBox.qtpl:10
	qs422016 := string(qb422016.B)
//line widgets/InfoBox.qtpl:10
	qt422016.ReleaseByteBuffer(qb422016)
//line widgets/InfoBox.qtpl:10
	return qs422016
//line widgets/InfoBox.qtpl:10
}
