// Code generated by qtc from "Modal.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line widgets/Modal.qtpl:2
package widgets

//line widgets/Modal.qtpl:2
import . "../types"

//line widgets/Modal.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line widgets/Modal.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line widgets/Modal.qtpl:4
func StreamModal(qw422016 *qt422016.Writer, opt *WidgetInfo) {
//line widgets/Modal.qtpl:4
	qw422016.N().S(`
<!-- The Modal -->
  <div class="modal fade" id="`)
//line widgets/Modal.qtpl:6
	qw422016.E().S(opt.Id)
//line widgets/Modal.qtpl:6
	qw422016.N().S(`">
    <div class="modal-dialog">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">`)
//line widgets/Modal.qtpl:12
	qw422016.E().S(opt.Heading)
//line widgets/Modal.qtpl:12
	qw422016.N().S(`</h4>
          <button type="button" class="close" data-dismiss="modal">×</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">
          `)
//line widgets/Modal.qtpl:18
	qw422016.E().S(opt.Body)
//line widgets/Modal.qtpl:18
	qw422016.N().S(` 
        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
        
      </div>
    </div>
  </div>
`)
//line widgets/Modal.qtpl:29
}

//line widgets/Modal.qtpl:29
func WriteModal(qq422016 qtio422016.Writer, opt *WidgetInfo) {
//line widgets/Modal.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line widgets/Modal.qtpl:29
	StreamModal(qw422016, opt)
//line widgets/Modal.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line widgets/Modal.qtpl:29
}

//line widgets/Modal.qtpl:29
func Modal(opt *WidgetInfo) string {
//line widgets/Modal.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
//line widgets/Modal.qtpl:29
	WriteModal(qb422016, opt)
//line widgets/Modal.qtpl:29
	qs422016 := string(qb422016.B)
//line widgets/Modal.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
//line widgets/Modal.qtpl:29
	return qs422016
//line widgets/Modal.qtpl:29
}
