// Code generated by qtc from "SelectRadio.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line widgets/SelectRadio.qtpl:2
package widgets

//line widgets/SelectRadio.qtpl:2
import . "../types"

//line widgets/SelectRadio.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line widgets/SelectRadio.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line widgets/SelectRadio.qtpl:4
func StreamSelectRadio(qw422016 *qt422016.Writer, opt *WidgetInfo) {
//line widgets/SelectRadio.qtpl:4
	qw422016.N().S(` 

`)
//line widgets/SelectRadio.qtpl:6
	if len(opt.Items) == 0 {
//line widgets/SelectRadio.qtpl:6
		qw422016.N().S(`

   <div>No Inputs provided </div>

`)
//line widgets/SelectRadio.qtpl:10
	} else {
//line widgets/SelectRadio.qtpl:10
		qw422016.N().S(`

`)
//line widgets/SelectRadio.qtpl:12
		for _, item := range opt.Items {
//line widgets/SelectRadio.qtpl:12
			qw422016.N().S(`

   <div class="form-check">
      <input class="form-check-input" type="radio" name="`)
//line widgets/SelectRadio.qtpl:15
			qw422016.E().S(item.Name)
//line widgets/SelectRadio.qtpl:15
			qw422016.N().S(`" id="`)
//line widgets/SelectRadio.qtpl:15
			qw422016.E().S(item.Id)
//line widgets/SelectRadio.qtpl:15
			qw422016.N().S(`" value="`)
//line widgets/SelectRadio.qtpl:15
			qw422016.E().S(item.Value)
//line widgets/SelectRadio.qtpl:15
			qw422016.N().S(`" 
`)
//line widgets/SelectRadio.qtpl:16
			if item.Value == opt.SelectedValue {
//line widgets/SelectRadio.qtpl:16
				qw422016.N().S(`checked`)
//line widgets/SelectRadio.qtpl:16
			}
//line widgets/SelectRadio.qtpl:16
			qw422016.N().S(` 
`)
//line widgets/SelectRadio.qtpl:17
			if item.Checked {
//line widgets/SelectRadio.qtpl:17
				qw422016.N().S(`checked`)
//line widgets/SelectRadio.qtpl:17
			}
//line widgets/SelectRadio.qtpl:17
			qw422016.N().S(` 
`)
//line widgets/SelectRadio.qtpl:18
			if item.Disabled {
//line widgets/SelectRadio.qtpl:18
				qw422016.N().S(`disabled`)
//line widgets/SelectRadio.qtpl:18
			}
//line widgets/SelectRadio.qtpl:18
			qw422016.N().S(` >
      <label class="form-check-label" for="`)
//line widgets/SelectRadio.qtpl:19
			qw422016.E().S(item.Id)
//line widgets/SelectRadio.qtpl:19
			qw422016.N().S(`">
         `)
//line widgets/SelectRadio.qtpl:20
			qw422016.E().S(item.Value)
//line widgets/SelectRadio.qtpl:20
			qw422016.N().S(` 
      </label>
   </div>

`)
//line widgets/SelectRadio.qtpl:24
		}
//line widgets/SelectRadio.qtpl:24
		qw422016.N().S(`

`)
//line widgets/SelectRadio.qtpl:26
	}
//line widgets/SelectRadio.qtpl:26
	qw422016.N().S(`

`)
//line widgets/SelectRadio.qtpl:28
}

//line widgets/SelectRadio.qtpl:28
func WriteSelectRadio(qq422016 qtio422016.Writer, opt *WidgetInfo) {
//line widgets/SelectRadio.qtpl:28
	qw422016 := qt422016.AcquireWriter(qq422016)
//line widgets/SelectRadio.qtpl:28
	StreamSelectRadio(qw422016, opt)
//line widgets/SelectRadio.qtpl:28
	qt422016.ReleaseWriter(qw422016)
//line widgets/SelectRadio.qtpl:28
}

//line widgets/SelectRadio.qtpl:28
func SelectRadio(opt *WidgetInfo) string {
//line widgets/SelectRadio.qtpl:28
	qb422016 := qt422016.AcquireByteBuffer()
//line widgets/SelectRadio.qtpl:28
	WriteSelectRadio(qb422016, opt)
//line widgets/SelectRadio.qtpl:28
	qs422016 := string(qb422016.B)
//line widgets/SelectRadio.qtpl:28
	qt422016.ReleaseByteBuffer(qb422016)
//line widgets/SelectRadio.qtpl:28
	return qs422016
//line widgets/SelectRadio.qtpl:28
}
