// Code generated by qtc from "SignIn.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// logourl: `https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg`

//line widgets/SignIn.qtpl:2
package widgets

//line widgets/SignIn.qtpl:2
import . "../types"

//line widgets/SignIn.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line widgets/SignIn.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line widgets/SignIn.qtpl:4
func StreamSignInForm(qw422016 *qt422016.Writer, opt *WidgetInfo) {
//line widgets/SignIn.qtpl:4
	qw422016.N().S(`
 <form class="form-signin">
      <img class="mb-4" src="`)
//line widgets/SignIn.qtpl:6
	qw422016.E().S(opt.LogoUrl)
//line widgets/SignIn.qtpl:6
	qw422016.N().S(`" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">`)
//line widgets/SignIn.qtpl:7
	qw422016.E().S(opt.Title)
//line widgets/SignIn.qtpl:7
	qw422016.N().S(`</h1>
      <label for="`)
//line widgets/SignIn.qtpl:8
	qw422016.E().S(opt.Id)
//line widgets/SignIn.qtpl:8
	qw422016.N().S(`" class="sr-only">Email Address</label>
      <input type="email" id="`)
//line widgets/SignIn.qtpl:9
	qw422016.E().S(opt.IdEmail)
//line widgets/SignIn.qtpl:9
	qw422016.N().S(`" class="form-control" placeholder="user@example.com" required autofocus>
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" id="`)
//line widgets/SignIn.qtpl:11
	qw422016.E().S(opt.IdPassword)
//line widgets/SignIn.qtpl:11
	qw422016.N().S(`" class="form-control" placeholder="Password" required>
`)
//line widgets/SignIn.qtpl:12
	if opt.RememberMe {
//line widgets/SignIn.qtpl:12
		qw422016.N().S(`
      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
`)
//line widgets/SignIn.qtpl:18
	}
//line widgets/SignIn.qtpl:18
	qw422016.N().S(`
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      <p class="mt-5 mb-3 text-muted">`)
//line widgets/SignIn.qtpl:20
	qw422016.E().S(opt.SubText)
//line widgets/SignIn.qtpl:20
	qw422016.N().S(`</p>
</form>
`)
//line widgets/SignIn.qtpl:22
}

//line widgets/SignIn.qtpl:22
func WriteSignInForm(qq422016 qtio422016.Writer, opt *WidgetInfo) {
//line widgets/SignIn.qtpl:22
	qw422016 := qt422016.AcquireWriter(qq422016)
//line widgets/SignIn.qtpl:22
	StreamSignInForm(qw422016, opt)
//line widgets/SignIn.qtpl:22
	qt422016.ReleaseWriter(qw422016)
//line widgets/SignIn.qtpl:22
}

//line widgets/SignIn.qtpl:22
func SignInForm(opt *WidgetInfo) string {
//line widgets/SignIn.qtpl:22
	qb422016 := qt422016.AcquireByteBuffer()
//line widgets/SignIn.qtpl:22
	WriteSignInForm(qb422016, opt)
//line widgets/SignIn.qtpl:22
	qs422016 := string(qb422016.B)
//line widgets/SignIn.qtpl:22
	qt422016.ReleaseByteBuffer(qb422016)
//line widgets/SignIn.qtpl:22
	return qs422016
//line widgets/SignIn.qtpl:22
}
