// Code generated by qtc from "TextLineInput.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line widgets/TextLineInput.qtpl:1
package widgets

//line widgets/TextLineInput.qtpl:1
import . "../types"

//line widgets/TextLineInput.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line widgets/TextLineInput.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line widgets/TextLineInput.qtpl:3
func StreamTextLineInput(qw422016 *qt422016.Writer, opt *WidgetInfo) {
//line widgets/TextLineInput.qtpl:3
	qw422016.N().S(`
     <div class="form-group">
        <label for="`)
//line widgets/TextLineInput.qtpl:5
	qw422016.E().S(opt.Id)
//line widgets/TextLineInput.qtpl:5
	qw422016.N().S(`">`)
//line widgets/TextLineInput.qtpl:5
	qw422016.E().S(opt.Label)
//line widgets/TextLineInput.qtpl:5
	qw422016.N().S(`</label>
        <input type="text" class="form-control" id="`)
//line widgets/TextLineInput.qtpl:6
	qw422016.E().S(opt.Id)
//line widgets/TextLineInput.qtpl:6
	qw422016.N().S(`" value="`)
//line widgets/TextLineInput.qtpl:6
	qw422016.E().S(opt.Value)
//line widgets/TextLineInput.qtpl:6
	qw422016.N().S(`" aria-describedby="`)
//line widgets/TextLineInput.qtpl:6
	qw422016.E().S(opt.IdDescription)
//line widgets/TextLineInput.qtpl:6
	qw422016.N().S(`" placeholder="`)
//line widgets/TextLineInput.qtpl:6
	qw422016.E().S(opt.Placeholder)
//line widgets/TextLineInput.qtpl:6
	qw422016.N().S(`" />
     </div>
`)
//line widgets/TextLineInput.qtpl:8
}

//line widgets/TextLineInput.qtpl:8
func WriteTextLineInput(qq422016 qtio422016.Writer, opt *WidgetInfo) {
//line widgets/TextLineInput.qtpl:8
	qw422016 := qt422016.AcquireWriter(qq422016)
//line widgets/TextLineInput.qtpl:8
	StreamTextLineInput(qw422016, opt)
//line widgets/TextLineInput.qtpl:8
	qt422016.ReleaseWriter(qw422016)
//line widgets/TextLineInput.qtpl:8
}

//line widgets/TextLineInput.qtpl:8
func TextLineInput(opt *WidgetInfo) string {
//line widgets/TextLineInput.qtpl:8
	qb422016 := qt422016.AcquireByteBuffer()
//line widgets/TextLineInput.qtpl:8
	WriteTextLineInput(qb422016, opt)
//line widgets/TextLineInput.qtpl:8
	qs422016 := string(qb422016.B)
//line widgets/TextLineInput.qtpl:8
	qt422016.ReleaseByteBuffer(qb422016)
//line widgets/TextLineInput.qtpl:8
	return qs422016
//line widgets/TextLineInput.qtpl:8
}
