// Code generated by qtc from "YesNoBoxVue.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line widgets/YesNoBoxVue.qtpl:2
package widgets

//line widgets/YesNoBoxVue.qtpl:2
import . "../types"

//line widgets/YesNoBoxVue.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line widgets/YesNoBoxVue.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line widgets/YesNoBoxVue.qtpl:4
func StreamYesNoBoxVue(qw422016 *qt422016.Writer, opt *WidgetInfo) {
//line widgets/YesNoBoxVue.qtpl:4
	qw422016.N().S(`
<template>
 <div>
      <div class="modal-header">
        <h5 class="modal-title">`)
//line widgets/YesNoBoxVue.qtpl:8
	qw422016.E().S(opt.Title)
//line widgets/YesNoBoxVue.qtpl:8
	qw422016.N().S(`</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>`)
//line widgets/YesNoBoxVue.qtpl:14
	qw422016.E().S(opt.Message)
//line widgets/YesNoBoxVue.qtpl:14
	qw422016.N().S(`</p>
      </div>
      <div class="modal-footer">
        <button type="button" v-on:click="yesCallback();" class="btn btn-primary">`)
//line widgets/YesNoBoxVue.qtpl:17
	qw422016.E().S(opt.YesButtonText)
//line widgets/YesNoBoxVue.qtpl:17
	qw422016.N().S(`</button>
        <button type="button" v-on:click="noCallback();" class="btn btn-secondary" data-dismiss="modal">`)
//line widgets/YesNoBoxVue.qtpl:18
	qw422016.E().S(opt.NoButtonText)
//line widgets/YesNoBoxVue.qtpl:18
	qw422016.N().S(`</button>
      </div>
  </div>
</template>
<script>
module.exports = {
    data: function() {
        return {
            who: 'world',
            yesCallback: function() {
               console.log("YES Callback called..")
               interact("`)
//line widgets/YesNoBoxVue.qtpl:29
	qw422016.E().S(opt.ScriptName)
//line widgets/YesNoBoxVue.qtpl:29
	qw422016.N().S(`", ":reply", ":exit 0")
               return true
            },
            noCallback: function() {
               console.log("NO Callback called..")
               interact("`)
//line widgets/YesNoBoxVue.qtpl:34
	qw422016.E().S(opt.ScriptName)
//line widgets/YesNoBoxVue.qtpl:34
	qw422016.N().S(`", ":reply", ":exit 1")
               return true
            },
      }
    },
}
</script>
`)
//line widgets/YesNoBoxVue.qtpl:41
}

//line widgets/YesNoBoxVue.qtpl:41
func WriteYesNoBoxVue(qq422016 qtio422016.Writer, opt *WidgetInfo) {
//line widgets/YesNoBoxVue.qtpl:41
	qw422016 := qt422016.AcquireWriter(qq422016)
//line widgets/YesNoBoxVue.qtpl:41
	StreamYesNoBoxVue(qw422016, opt)
//line widgets/YesNoBoxVue.qtpl:41
	qt422016.ReleaseWriter(qw422016)
//line widgets/YesNoBoxVue.qtpl:41
}

//line widgets/YesNoBoxVue.qtpl:41
func YesNoBoxVue(opt *WidgetInfo) string {
//line widgets/YesNoBoxVue.qtpl:41
	qb422016 := qt422016.AcquireByteBuffer()
//line widgets/YesNoBoxVue.qtpl:41
	WriteYesNoBoxVue(qb422016, opt)
//line widgets/YesNoBoxVue.qtpl:41
	qs422016 := string(qb422016.B)
//line widgets/YesNoBoxVue.qtpl:41
	qt422016.ReleaseByteBuffer(qb422016)
//line widgets/YesNoBoxVue.qtpl:41
	return qs422016
//line widgets/YesNoBoxVue.qtpl:41
}
