// Code generated by qtc from "YesNoBox.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line widgets/YesNoBox.qtpl:2
package widgets

//line widgets/YesNoBox.qtpl:2
import . "../types"

//line widgets/YesNoBox.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line widgets/YesNoBox.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line widgets/YesNoBox.qtpl:4
func StreamYesNoBox(qw422016 *qt422016.Writer, opt *WidgetInfo) {
//line widgets/YesNoBox.qtpl:4
	qw422016.N().S(`
      <div class="modal-header">
        <h5 class="modal-title">`)
//line widgets/YesNoBox.qtpl:6
	qw422016.E().S(opt.Title)
//line widgets/YesNoBox.qtpl:6
	qw422016.N().S(`</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>`)
//line widgets/YesNoBox.qtpl:12
	qw422016.E().S(opt.Message)
//line widgets/YesNoBox.qtpl:12
	qw422016.N().S(`</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary">`)
//line widgets/YesNoBox.qtpl:15
	qw422016.E().S(opt.YesButtonText)
//line widgets/YesNoBox.qtpl:15
	qw422016.N().S(`</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">`)
//line widgets/YesNoBox.qtpl:16
	qw422016.E().S(opt.NoButtonText)
//line widgets/YesNoBox.qtpl:16
	qw422016.N().S(`</button>
      </div>
`)
//line widgets/YesNoBox.qtpl:18
}

//line widgets/YesNoBox.qtpl:18
func WriteYesNoBox(qq422016 qtio422016.Writer, opt *WidgetInfo) {
//line widgets/YesNoBox.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
//line widgets/YesNoBox.qtpl:18
	StreamYesNoBox(qw422016, opt)
//line widgets/YesNoBox.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line widgets/YesNoBox.qtpl:18
}

//line widgets/YesNoBox.qtpl:18
func YesNoBox(opt *WidgetInfo) string {
//line widgets/YesNoBox.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
//line widgets/YesNoBox.qtpl:18
	WriteYesNoBox(qb422016, opt)
//line widgets/YesNoBox.qtpl:18
	qs422016 := string(qb422016.B)
//line widgets/YesNoBox.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
//line widgets/YesNoBox.qtpl:18
	return qs422016
//line widgets/YesNoBox.qtpl:18
}
