// Code generated by qtc from "ScriptsTableVue.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/ScriptsTableVue.qtpl:1
package views

//line views/ScriptsTableVue.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/ScriptsTableVue.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/ScriptsTableVue.qtpl:1
func StreamScriptsTableVue(qw422016 *qt422016.Writer) {
//line views/ScriptsTableVue.qtpl:1
	qw422016.N().S(`
   <div id="VueScriptsTable">
       <scripts-table></scripts-table>
       <script-modal></script-modal>
   </div>
`)
//line views/ScriptsTableVue.qtpl:6
}

//line views/ScriptsTableVue.qtpl:6
func WriteScriptsTableVue(qq422016 qtio422016.Writer) {
//line views/ScriptsTableVue.qtpl:6
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/ScriptsTableVue.qtpl:6
	StreamScriptsTableVue(qw422016)
//line views/ScriptsTableVue.qtpl:6
	qt422016.ReleaseWriter(qw422016)
//line views/ScriptsTableVue.qtpl:6
}

//line views/ScriptsTableVue.qtpl:6
func ScriptsTableVue() string {
//line views/ScriptsTableVue.qtpl:6
	qb422016 := qt422016.AcquireByteBuffer()
//line views/ScriptsTableVue.qtpl:6
	WriteScriptsTableVue(qb422016)
//line views/ScriptsTableVue.qtpl:6
	qs422016 := string(qb422016.B)
//line views/ScriptsTableVue.qtpl:6
	qt422016.ReleaseByteBuffer(qb422016)
//line views/ScriptsTableVue.qtpl:6
	return qs422016
//line views/ScriptsTableVue.qtpl:6
}

//line views/ScriptsTableVue.qtpl:9
func StreamVueComponent_ScriptsTable(qw422016 *qt422016.Writer) {
//line views/ScriptsTableVue.qtpl:9
	qw422016.N().S(`
Vue.component('scripts-table', httpVueLoader("/vue/components/scripts-table.vue"))
Vue.component('script-modal', httpVueLoader("/vue/components/script-modal.vue"))
Vue.component('script-state-banner', httpVueLoader("/vue/components/script-state-banner.vue"))

`)
//line views/ScriptsTableVue.qtpl:14
}

//line views/ScriptsTableVue.qtpl:14
func WriteVueComponent_ScriptsTable(qq422016 qtio422016.Writer) {
//line views/ScriptsTableVue.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/ScriptsTableVue.qtpl:14
	StreamVueComponent_ScriptsTable(qw422016)
//line views/ScriptsTableVue.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line views/ScriptsTableVue.qtpl:14
}

//line views/ScriptsTableVue.qtpl:14
func VueComponent_ScriptsTable() string {
//line views/ScriptsTableVue.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
//line views/ScriptsTableVue.qtpl:14
	WriteVueComponent_ScriptsTable(qb422016)
//line views/ScriptsTableVue.qtpl:14
	qs422016 := string(qb422016.B)
//line views/ScriptsTableVue.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
//line views/ScriptsTableVue.qtpl:14
	return qs422016
//line views/ScriptsTableVue.qtpl:14
}
